### PR TITLE
Handle buffer variable not being set

### PR DESCRIPTION
**Pull request by saep**
I've skimmed over your code and I think that `closeInfoWindows` would also error if you have windows open where your plugin doesn't set the `cornelis_window` buffer variable. Otherwise I'll have to dive deeper to fix your issue: https://github.com/neovimhaskell/nvim-hs/issues/94

### CODE REVIEW

**Comment by isovector** [comment]
Oh, a marshalling error makes a lot of sense. Yeah, I havent managed to get this working at all, and that would explain why.

Thanks for the fix! Maybe it would also be worth encoding this more directly in the API, with the `*_get_var` functions returning a more error-aware type?

**Comment by isovector** [comment]
Thanks for the PR! I can confirm that it fixes the issue --- though I'm not quite sure why.

**Comment by saep** [comment]
I tested it in the repl and it throws an exception.

If you start ghci with `NVIM_LISTEN_ADDRESS` set (or from within neovim), you can import `Neovim.Debug` and test out remote functions with `debug' $ vim_get_var "whatever"` and see the result.

The variable is only set if your plugin sets it as far as i could see. The first time it is started, no buffers have the variable set, so it would throw an exception for every window. On recompiling and restarting, it can close windows where the variable is set in the shown buffer. I think that calling `closeInfoWindows` is mainly useful to synchronize the internal state of your plugin with the state of the editor by making sure that no info windows exist.

**Comment by isovector** [comment]
I guess I'm confused as to why this exception happens in the first place. Presumably it's just what nvim does when the variable doesn't exist? If so, I'd suggest we patch this downstream in `nvim-hs` somehow, either via a helper function and some haddock on `vim_get_var` (and friends), or do it directly when generating `vim_get_var`.

**Pull request merged**
