### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by malob**
Highlights:
* Adds CI for Nix packages
* Fixes Stack test jobs so they actually run on the 3 OSs.
* Adds caching for `~/.stack` and project `.stack-work` to speed up CI builds.
* Installs Neovim and Agda so tests actually run.

With those changes CI fails for Stack tests on Linux and macOS, and build is failing on Windows. I'll leave figuring that out to someone who understands the codebase better.

### CODE REVIEW

**Comment by malob** [comment]
(Caches only get updated when the jobs succeeds, so we won't see any benefits right now.)

**Comment by isovector** [comment]
Tests are now working (but 20% flakey :worried: ) in `master`.

**Comment by isovector** [comment]
Tests are passing for me but don't seem to be in CI. My suspicion is it's the delay in waiting for Agda to respond. I'll see if I can make that more robust sometime later today.

**Comment by malob** [comment]
@isovector, with my last commit I've refactored the CI stuff so that building the package and tests with Stack is done with a separate job, which when it succeeds, caches the build artifacts. Then, there's a separate job that only runs if the former succeeds, which loads the caches, and actually runs the tests. This should make the feedback loop for you figuring out how to get the tests to pass on the CI much faster (~2 mins to see if tests fail on CI instead of 10–20 mins).

The best workflow would probably be to merge this PR, then make a branch off of `master` and push it to GitHub and let the CI run until the builds succeeds and the build artifacts get cached (caches aren't shared between branches). Then you can (force-)push to that branch to your hearts content to try and get the tests working.

**Comment by isovector** [comment]
@malob thanks so much! I have been avoiding figuring out how to do this in CI because it sounded extremely painful. I really really appreciate you dropping in with such a marvelous PR.

**Pull request merged**
